### PR TITLE
fix Windows tests, 'call conda activate'

### PR DESCRIPTION
**Pull request by mbargull**
Checklist
* [x] Used a fork of the feedstock to propose changes

xref: https://github.com/conda-forge/conda-feedstock/issues/49#issuecomment-390519997 (cc: @jakirkham, @kalefranz)

I'm not sure when that temporary directory for which all those `Access is denied` errors happen comes into play.

But the logs indicate (https://ci.appveyor.com/project/conda-forge/conda-feedstock/build/1.0.130/job/9wf7g6m38thf4o2e#L1261) that https://github.com/conda-forge/conda-feedstock/blob/c999046e2a45e1539b507bc1a3a1a0c3b8815d6d/recipe/run_test.bat#L23 is the last command that is run by the tests. That one need to be changed to `call`.
(I didn't change the build number because I suppose a new build isn't necessary -- unless the tests fail now and indicate a faulty build, of course.)

### CODE REVIEW

**Comment by scopatz** [comment]
LGTM - aiting on CI

**Comment by mbargull** [comment]
Duh... the same for `deactivate`, too, of course.

**Comment by scopatz** [comment]
There are a lot of `Access is denied.` messages at the end of the build.  Any idea what that is about?

**Comment by mbargull** [comment]
@msarahan: Do you have any idea what might be happening here?
I assume --  given the log is not scrambled in any way -- that part of the build log,
https://ci.appveyor.com/project/conda-forge/conda-feedstock/build/1.0.133/job/y2f8pigca3wwvqb4#L1303
to
https://ci.appveyor.com/project/conda-forge/conda-feedstock/build/1.0.133/job/y2f8pigca3wwvqb4#L1736,
corresponds to
https://github.com/conda/conda-build/blob/3.10.4/conda_build/build.py#L2022-L2032.
Hence those `Access denied`s should come from
https://github.com/conda/conda-build/blob/3.10.4/conda_build/build.py#L2031.

**Comment by mbargull** [comment]
There is a similar `Access denied` that is the reason for gh-49: https://ci.appveyor.com/project/conda-forge/conda-feedstock/build/1.0.130/job/9wf7g6m38thf4o2e#L1740:
```
upload_or_check_non_existence .\recipe conda-forge --channel=main -m .ci_support\%CONFIG%.yaml
Adding in variants from internal_defaults
Adding in variants from .ci_support\win_python3.6.yaml
Attempting to finalize metadata for conda
Solving environment: ...working... done
Solving environment: ...working... done
Processing conda
Traceback (most recent call last):
  File "C:\Miniconda36-x64\Scripts\upload_or_check_non_existence.py", line 131, in <module>
    main()
  File "C:\Miniconda36-x64\Scripts\upload_or_check_non_existence.py", line 121, in main
    upload(cli, fname, owner, channel)
  File "C:\Miniconda36-x64\Scripts\upload_or_check_non_existence.py", line 68, in upload
    env=os.environ)
  File "C:\Miniconda36-x64\lib\contextlib.py", line 88, in __exit__
    next(self.gen)
  File "C:\Miniconda36-x64\Scripts\upload_or_check_non_existence.py", line 27, in get_temp_token
    shutil.rmtree(dn)
  File "C:\Miniconda36-x64\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Miniconda36-x64\lib\shutil.py", line 389, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Miniconda36-x64\lib\shutil.py", line 387, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\tmp7dsv8puk\\binstar.token'
```
Note that this one happens in `upload_or_check_non_existence.py` and **not** in `conda-build`.

**Comment by kenodegard** [comment]
moot with https://github.com/conda-forge/conda-feedstock/pull/209

**Pull request closed without merging**
