### PR TITLE
conda 4.4.11

### PR DESCRIPTION
**Pull request by kalefranz**
Conda 4.4 is ready to go with conda-build-all.  See https://github.com/conda-tools/conda-build-all/pull/96

### CODE REVIEW

**Comment by kalefranz** [comment]
@jakirkham Any hints about what's going on with linting here?

**Comment by mbargull** [comment]
https://github.com/conda/conda/blob/4.4.11/utils/functions.sh#L17
https://github.com/conda/conda/blob/4.4.11/utils/functions.sh#L79

**Comment by kalefranz** [comment]
https://github.com/conda/conda/blob/4.4.11/utils/functions.sh#L35

**Comment by mbargull** [comment]
https://github.com/conda/conda/blob/4.4.11/conda.recipe/setup.py#L6
https://github.com/conda/conda/blob/4.4.11/conda.recipe/setup.py#L52-L57
?

**Comment by mbargull** [comment]
I guess, since that `setup.py` doesn't use `setuptools`, no entry point is created and hence `$PREFIX/bin/conda` isn't there yet when `build.sh` tries to run it.

**Comment by mbargull** [comment]
I think I'd just use `$PREFIX/bin/python -m conda info` then. What do you think?

**Comment by marscher** [comment]
On 03.03.2018 17:05, Marcel Bargull wrote:
> I think I'd just use `$PREFIX/bin/python -m conda info` then. What do you think?
> 

You should add the following to the build section to get the correct 
entry point:

```
build:
   entry_points:
     - conda: conda.cli:main
     - conda-env: conda_env.cli.main:main
```

**Comment by mbargull** [comment]
This is about running `conda` during the build, not afterwards.

**Comment by dougalsutherland** [comment]
Linter error is because the linter doesn't know about `run_constrained`. It was solved by https://github.com/conda-forge/conda-smithy/pull/554, but that's not in a release yet.

**Comment by dougalsutherland** [comment]
Got the build working, but it fails at test time because it's using the wrong `conda` there too. `which -a conda` says
```
/feedstock_root/build_artefacts/conda_1522159160013/_t_env/bin/conda
/feedstock_root/build_artefacts/conda_1522159160013/_t_env/bin/conda
/feedstock_root/build_artefacts/conda_1522159160013/_t_env/bin/conda
/opt/conda/bin/conda
```
but then `conda --version` gives 4.3.34. Something about installing it in a test env?

**Comment by mbargull** [comment]
Now that's odd...
```
+ . /feedstock_root/build_artefacts/conda_1522159655204/_t_env/etc/profile.d/conda.sh
++ _CONDA_EXE=/feedstock_root/build_artefacts/conda_1522159655204/_t_env/bin/conda
...
++ conda --version
++ '[' 1 -ge 1 ']'
++ local cmd=--version
++ shift
++ case "$cmd" in
++ /feedstock_root/build_artefacts/conda_1522159655204/_t_env/bin/conda --version
+ [[ conda 4.3.34 == \c\o\n\d\a\ \4\.\4\.\1\1 ]]
```
clearly shows that `_CONDA_EXE` is set correctly and that we run the shell function's code.
For debugging purposes, can you add
```yaml
  - head -n1 "$_CONDA_EXE"
  - which -a python
  - python -c 'import conda; print(conda.__version__)'
  - python -m conda --version
  - python "$_CONDA_EXE"
  - $(sed 's/^#!\s*//;q' "$_CONDA_EXE") -c 'import conda; print(conda.__version__)'
  - $(sed 's/^#!\s*//;q' "$_CONDA_EXE") -m conda --version
```
to the test commands?

**Comment by mbargull** [comment]
Before the version comparison, of course.

**Comment by mbargull** [comment]
Thanks @dougalsutherland!
Looks like what I suspected:
```
+ head -n1 /feedstock_root/build_artefacts/conda_1522329199678/_t_env/bin/conda
#!/opt/conda/bin/python
+ which -a python
/feedstock_root/build_artefacts/conda_1522329199678/_t_env/bin/python
/feedstock_root/build_artefacts/conda_1522329199678/_t_env/bin/python
/feedstock_root/build_artefacts/conda_1522329199678/_t_env/bin/python
/opt/conda/bin/python
/usr/bin/python
+ python -c 'import conda; print(conda.__version__)'
4.4.11
+ python -m conda --version
conda 4.4.11
+ python /feedstock_root/build_artefacts/conda_1522329199678/_t_env/bin/conda
usage: conda [-h] [-V] command ...

conda is a tool for managing and deploying applications, environments and packages.

Options:

positional arguments:
  command
    clean        Remove unused packages and caches.
    config       Modify configuration values in .condarc. This is modeled
                 after the git config command. Writes to the user .condarc
                 file (/home/conda/.condarc) by default.
    create       Create a new conda environment from a list of specified
                 packages.
    help         Displays a list of available conda commands and their help
                 strings.
    info         Display information about current conda install.
    install      Installs a list of packages into a specified conda
                 environment.
    list         List linked packages in a conda environment.
    package      Low-level conda package utility. (EXPERIMENTAL)
    remove       Remove a list of packages from a specified conda environment.
    uninstall    Alias for conda remove. See conda remove --help.
    search       Search for packages and display associated information. The
                 input is a MatchSpec, a query language for conda packages.
                 See examples below.
    update       Updates conda packages to the latest compatible version. This
                 command accepts a list of package names and updates them to
                 the latest versions that are compatible with all other
                 packages in the environment. Conda attempts to install the
                 newest versions of the requested packages. To accomplish
                 this, it may update some packages that are already installed,
                 or install additional packages. To prevent existing packages
                 from updating, use the --no-update-deps option. This may
                 force conda to install older versions of the requested
                 packages, and it does not prevent additional dependency
                 packages from being installed. If you wish to skip dependency
                 checking altogether, use the '--force' option. This may
                 result in an environment with incompatible packages, so this
                 option must be used with great caution.
    upgrade      Alias for conda update. See conda update --help.

optional arguments:
  -h, --help     Show this help message and exit.
  -V, --version  Show the conda version number and exit.

conda commands available from other packages:
  env
++ sed 's/^#!\s*//;q' /feedstock_root/build_artefacts/conda_1522329199678/_t_env/bin/conda
+ /opt/conda/bin/python -c 'import conda; print(conda.__version__)'
4.3.34
++ sed 's/^#!\s*//;q' /feedstock_root/build_artefacts/conda_1522329199678/_t_env/bin/conda
+ /opt/conda/bin/python -m conda --version
conda 4.3.34
++ conda --version
++ '[' 1 -ge 1 ']'
++ local cmd=--version
++ shift
++ case "$cmd" in
++ /feedstock_root/build_artefacts/conda_1522329199678/_t_env/bin/conda --version
+ [[ conda 4.3.34 == \c\o\n\d\a\ \4\.\4\.\1\1 ]]
+ exit 1
TESTS FAILED: conda-4.4.11-py36_0.tar.bz2
+ exit 1
Exited with code 1
```
=> the shebang of `/feedstock_root/build_artefacts/conda_1522329199678/_t_env/bin/conda` uses the wrong interpreter.
I haven't yet looked into why, though.

**Comment by dougalsutherland** [comment]
Now that we have https://github.com/conda-forge/conda-forge-build-setup-feedstock/pull/95, I think we're probably safe to actually publish conda 4.4/4.5 on conda-forge -- which we should try to do soon if we can because of #43.

@mbargull @kalefranz, any chance that just updating to the latest conda 4.5 would fix this :crossed_fingers:?

**Comment by kalefranz** [comment]
> any chance that just updating to the latest conda 4.5 would fix this

I believe the answer is, yes.

**Comment by dougalsutherland** [comment]
Okay, well let's do try that then. There's no particular reason we need to publish 4.4, right?

I'll update the PR unless you're doing it right now.

**Comment by dougalsutherland** [comment]
Nope, same problem. :cry:

**Comment by jakirkham** [comment]
Thanks all for working on this. Created PR ( https://github.com/conda-forge/conda-feedstock/pull/44 ) based on a simplified version of the changes here that seemed to work on Unix platforms at least (hopefully Windows too 🍀). Feedback welcome. :)

**Pull request closed without merging**
