### PR TITLE
Release 4.2.13

### PR DESCRIPTION
**Pull request by jakirkham**
Replaces PR ( https://github.com/conda-forge/conda-feedstock/pull/13 ).

```markdown
## 4.2.13

### Improvements
* double/extend http timeouts (#3831)
* let descriptive http errors cover more http exceptions (#3834)
* backport some conda-build configuration (#3875)

### Non-User-Facing Changes
* flake8 E116, E121, & E123 enabled (#3883)
```

cc @jjhelmus

### CODE REVIEW

**Comment by jakirkham** [comment]
My only remaining concern is if the `conda` `4.2.x` series has anything to do with issue ( https://github.com/conda-forge/conda-smithy/issues/351 ). It may not, but it would be nice to confirm before we roll it out.

**Comment by jjhelmus** [comment]
I'm in favor of merging this, do others agree?  conda build `1.x` can still be used with this version of conda and without a good method of debugging the AppVeyor VS2008 slow startup/memory issue (conda-forge/conda-smithy#351) I don't think we can do much to determine if the `4.2.x` series is causing this issue.  If this does cause an issue conda `4.1.x` could be pinned in `conda-forge-build-setup` until a fix can be created.

**Comment by ocefpaf** [comment]
Agreed.

**Comment by jakirkham** [comment]
Also agree.

**Comment by jakirkham** [comment]
Thus far I'm not seeing issue ( https://github.com/conda-forge/conda-smithy/issues/351 ) resurface. So let's continue to not worry about it yet.

**Pull request merged**
