### PR TITLE
codesign osx-arm64 binaries

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Applies https://github.com/conda/conda/pull/10260

### CODE REVIEW

**Comment by erykoff** [comment]
I can confirm that this PR works to sign re-located binaries on osx-arm64 at installation time so that they are able to run.

**Review by scopatz — CHANGES_REQUESTED** [review]
This PR has not been merged in conda. We should wait for at least that

**Comment by isuruf** [comment]
I've said this before, we make lots of changes to other packages to make them work on platforms that upstream don't support. I don't see how conda is any different.

**Comment by scopatz** [comment]
I have two main thoughts on that: 

1. Most of the time when we patch other packages, we are either altering the build system or making other changes to allow the package to work in a conda environment. We specifically aren't touching APIs.
2. There is no sense in which an unmerged patch can be reasonably called part of that package. It hasn't gone through the full review process of that project and it would be false advertising to call such changes (especially public API facing ones) as part of that package.

**Comment by isuruf** [comment]
1. We are doing what is minimally necessary for conda to work on this platform. We've added environment variables to `python` package, to `clang` package that changes the behaviour entirely depending on that env variable. IMHO, this change does nothing of the sort.

2. By the same logic, we can't call the `python` that we ship as `python` as we change a lot of its behaviour. Have a look at `python-feedstock`. It has dozens of patches that change the behaviour and has never been sent upstream.

cc @conda-forge/core

**Comment by scopatz** [comment]
conda really isn't a project on the scale of python. Is it is problem to wait for a review on conda?

**Review by beckermr — APPROVED** [review]

**Review by scopatz — APPROVED** [review]

**Pull request merged**
