### PR TITLE
WIP: Try except patch

### PR DESCRIPTION
**Pull request by hmaarrfk**
@ocefpaf this is a draft for what we discussed around try/except.

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge-admin please restart cis

**Comment by ocefpaf** [comment]
LGTM! Thanks!! @jezdez the discussion for this PR is in https://github.com/conda-forge/conda-feedstock/pull/135, do you mind taking a look if you have some time?

**Comment by ocefpaf** [comment]
@jezdez ignore the ping.

@hmaarrfk I tested a simpler soluton that @isuruf's sent me. I'll send a PR and that is probably better than the try/except complextity. Sorry about the wild goose chase. Are you OK closing this one?

**Comment by hmaarrfk** [comment]
Closed in favor of https://github.com/conda-forge/conda-feedstock/pull/150

**Pull request closed without merging**
