### PR TITLE
Adds missing `conda-env` entrypoint

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/conda-forge/conda-feedstock/issues/11

This adds an entry point for `conda-env` to the recipe.

cc @frol @kalefranz

### CODE REVIEW

**Comment by frol** [comment]
I confirm that this works for me.

**Comment by frol** [comment]
Though, I think, `pyyaml` dependency should be also stated explicitly.

**Comment by jakirkham** [comment]
Thanks for checking. Yeah it was failing without `pyyaml` so adding it makes sense. Though I'm not sure when it got added as a dependency or why it doesn't appear in any of the canonical `conda` recipe sources.

**Comment by jakirkham** [comment]
Could you please look at this as soon as you have a chance, @kalefranz ?

**Comment by frol** [comment]
This is really odd that `pyyaml` was never listed as `conda-env` dependency while it is obviously required for parsing `environment.yml`.

**Comment by kalefranz** [comment]
LGTM.  I didn't realize conda-env was still using pyyaml.  I actually thought I had already moved it over to ruamel_yaml.  It'll be fixed in the next conda patch release probably coming Monday.
https://github.com/conda/conda/pull/3740

But until then, it's correct to have pyyaml as a dependency.

**Comment by jakirkham** [comment]
So if you are making another release today, should we just update this for the new release or would you rather get this out now?

**Comment by kalefranz** [comment]
I'm sick today. Fever and all. Probably will have to wait till tomorrow

**Comment by jakirkham** [comment]
Sorry to hear that. Hope you feel better.

**Comment by jakirkham** [comment]
Replacing with PR ( https://github.com/conda-forge/conda-feedstock/pull/13 ), which releases `4.2.12`.

**Pull request closed without merging**
