### PR TITLE
conda 24.11.2

### PR DESCRIPTION
**Pull request by kenodegard**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by kenodegard** [comment]
@conda-forge-admin, please rerender

**Comment by kenodegard** [comment]
@beckermr the failing test is for the downstream `conda-smithy` tests, looking at the failure statement it would appear to be a false negative

should we just skip the downstream tests for now and/or is this something to be fixed in `conda-smithy`'s tests?

**Comment by beckermr** [comment]
Yep, but let's skip just osx for now.

**Comment by beckermr** [comment]
We can file an issue on smithy as well. I do not understand why that test is failing, so it will need some investigation.

**Comment by jjerphan** [comment]
Thank you for publishing this bug fix release.

**Review by dbast — APPROVED** [review]

**Pull request merged**
