### PR TITLE
conda v22.9.0 #2

### PR DESCRIPTION
**Pull request by jezdez**
Replacing #175.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jezdez** [comment]
@conda-forge-admin, please rerender

**Comment by dbast** [comment]
@jezdez Is that remaining patch intended to be upstreamed, so that it does not require forward porting again with a new conda version?

**Comment by jakirkham** [comment]
Was there some discussion about the move to CalVer somewhere?

**Comment by travishathaway** [comment]
@jakirkham,

CalVer is outlined in [CEP 8](https://github.com/conda-incubator/ceps/blob/main/cep-8.md) and the voting/discussion happen [on this pull request](https://github.com/conda-incubator/ceps/pull/26).

**Comment by beckermr** [comment]
LGTM!

I made an announcement on the conda-forge side since this is a pretty big change.

https://github.com/conda-forge/conda-forge.github.io/commit/498b3b2ec33e55827680a3d1289eb472039632d4

**Review by beckermr — APPROVED** [review]

**Comment by jezdez** [comment]
Thank you @beckermr!

**Comment by jaimergp** [comment]
We might need a new build, there are some dependency changes that didn't make it to this PR:

[Check the cross-repo diff.](https://github.com/conda-forge/conda-feedstock/compare/main...AnacondaRecipes:conda-feedstock:master#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9a)

image

**Comment by jaimergp** [comment]
Well the diff was a bit more dramatic than needed. It's only `ruamel_yaml`.

PR here https://github.com/conda-forge/conda-feedstock/pull/177

**Comment by beckermr** [comment]
We should mark the old one as broken if needed.

**Comment by beckermr** [comment]
Not needed. Simply a looser pin.

**Pull request merged**
