### PR TITLE
Adjust `ruamel_yaml` version range

### PR DESCRIPTION
**Pull request by jaimergp**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Sync with [defaults](https://github.com/AnacondaRecipes/conda-feedstock/blob/92ac6eed450ce4ef3ce5585dc13a9c2a9b9ecc06/recipe/meta.yaml#L53) and [upstream](https://github.com/conda/conda/blob/60e11b4f1859874c1cb1a3ae324e599e0867a086/recipe/meta.yaml#L43)

### CODE REVIEW

**Comment by jaimergp** [comment]
I am not sure this is needed after all, `ruamel_yaml` was only published up to 0.15.x on both conda-forge and defaults 🤷

**Comment by beckermr** [comment]
Better to have it correct instead of relying on the non-existence of something.

**Review by beckermr — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks Jaime & Matt! 🙏

Should we do a repodata hotfix too?

**Comment by beckermr** [comment]
The previous build had a tighter constraint so no need for a hot fix afaik.

**Pull request merged**
