### PR TITLE
Update maintainers

### LINKED ISSUE #188: Are all maintainers of this feedstock still active?
### Comment:

The feedstock recipe contains [a list of maintainers](https://github.com/conda-forge/conda-feedstock/blob/269508f2e123b538c922cd62fb9b439a3174c288/recipe/meta.yaml#L109-L121) that IMO are not all active. I'd like to clean up the list to be able to know who to rely on, when we ship releases of conda to conda-forge.

@conda-forge/conda, please respond by selecting if you're still interested in helping with maintenance of this feedstock in the next few weeks (until the end of the year):

- [x] isuruf
- [x] jakirkham
- [ ] kalefranz
- [ ] mingwandroid
- [ ] msarahan
- [ ] mwcraig
- [x] ocefpaf
- [ ] patricksnape
- [ ] pelson
- [ ] scopatz
- [x] mbargull
- [x] jezdez

### PR DESCRIPTION
**Pull request by jezdez**
Fix #188

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jezdez** [comment]
@conda-forge-admin, please rerender

**Comment by kenodegard** [comment]
per https://github.com/conda-forge/conda-feedstock/pull/200#issuecomment-1444194464 we should add both @dbast and myself as maintainers

**Comment by jezdez** [comment]
@kenodegard Updated!

**Comment by jezdez** [comment]
@isuruf do you want to take a look at this before merging?

**Pull request merged**
