### PR TITLE
Release 4.4.0rc1

### PR DESCRIPTION
**Pull request by noahp**
### Changes
Pre-release for minor rev update 4.4. Quite a few changes:
https://github.com/conda/conda/compare/4.3.27...4.4.0rc1

### CODE REVIEW

**Comment by jakirkham** [comment]
A lot of our build tools will need to be updated to support `conda` 4.4.0. So that will need to happen before we release `conda` 4.4.0.

Also given this is an `rc` we don't release these under `main`, but under a different label. Though this is not totally finalized. ( https://github.com/conda-forge/conda-forge-enhancement-proposals/pull/3 )

**Comment by noahp** [comment]
Yup, makes a lot of sense, will decline! Much thanks for the info.

**Comment by jakirkham** [comment]
Sorry, unclear on what you are declining. 😕

**Comment by noahp** [comment]
Apologies- I'm going to close this pr now and take a look at what it's going to take to update the tooling (and the rc labeling proposal).

**Comment by jakirkham** [comment]
No need to apologize. Happy to point you to relevant issues if you are interested.

**Pull request closed without merging**
