### PR TITLE
update to 4.3.29

### PR DESCRIPTION
**Pull request by kalefranz**

### CODE REVIEW

**Comment by scopatz** [comment]
LGTM! Thanks @kalefranz

**Comment by kalefranz** [comment]
This should be a high-priority update to help combat https://github.com/conda/conda/issues/6096.

That issue happens when users updated to conda 4.3.28 via `defaults`, and then switched channel priority and downgraded to 4.3.27 via `conda-forge`.

4.3.29 is currently in defaults.  It should also be pushed out to conda-forge to prevent people currently running with conda 4.3.28 from running into breakage.

**Comment by kalefranz** [comment]
Thanks @scopatz.  I've asked @mingwandroid and @jjhelmus to jump on this too.  Should be merged as soon as it's all green.  I don't expect an issue.  Except looks like the macOS Travis workers are *really* backed up right now :(

**Comment by ocefpaf** [comment]
There is no reason for OS X to fail and, b/c this is a special case, let's merge to cash Windows and Linux packages and monitor the OS X build in master.

**Pull request merged**
