### PR TITLE
Release 4.2.16

### PR DESCRIPTION
**Pull request by jakirkham**
```markdown
## 4.2.16 (2017-01-20)

### Improvements
* vendor url parsing from urllib3 (#4289)
* workaround for symlink race conditions on activate (#4346)

### Bug Fixes
* do not replace \ with / in file:// URLs on Windows (#4269)
* include aliases for first command-line argument (#4279)
* fix for multi-line FTP status codes (#4276)
* fix errors with unknown type channels (#4291)
* change sys.exit to raise UpgradeError when info/files not found (#4388)

### Non-User-Facing Changes
* start using doctests in test runs and coverage (#4304)
* additional package pinning tests (#4312)


## 4.2.15 (2017-01-10)

### Improvements
* use 'post' instead of 'dev' for commits according to PEP-440 (#4234)
* do not use IFS to find activate/deactivate scripts to source (#4243)
* fix relative path to python in activate.bat (#4244)

### Bug Fixes
* replace sed with python for activate and deactivate #4257


## 4.2.14 (2017-01-07)

### Improvements
* use install.rm_rf for TemporaryDirectory cleanup (#3425)
* improve handling of local dependency information (#2107)
* add default channels to exports for Windows and Unix (#4103)
* make subdir configurable (#4178)

### Bug Fixes
* fix conda/install.py single-file behavior (#3854)
* fix the api->conda substitution (#3456)
* fix silent directory removal (#3730)
* fix location of temporary hard links of index.json (#3975)
* fix potential errors in multi-channel export and offline clone (#3995)
* fix auxlib/packaging, git hashes are not limited to 7 characters (#4189)
* fix compatibility with requests >=2.12, add pyopenssl as dependency (#4059)
* fix #3287 activate in 4.1-4.2.3 clobbers non-conda PATH changes (#4211)

### Non-User-Facing Changes
* fix open-ended test failures relating to python 3.6 release (#4166)
* allow args passed to cli.main() (#4193, #4200, #4201)
* test against python 3.6 (#4197)
```

### CODE REVIEW

**Comment by jakirkham** [comment]
Do you have any idea what is going on here, @msarahan? It seems like the subsequent environment is not being created correctly. 😕

**Comment by jakirkham** [comment]
Apparently `conda` 4.2.16 breaks `conda-smithy`. 😒 As I'm trying to do a release a new version of `conda-smithy` and don't have time to sort out the cause of this issue right now, I have pulled this version of `conda`. This rolls us back to 4.2.13, which seems to work ok.

**Comment by jjhelmus** [comment]
Given how brittle `conda-smithy` has been with updates to `conda` would it make sense to pin the run requirements for `conda-smithy` to a specific version of `conda`?

**Comment by jakirkham** [comment]
We could. The problem is `conda` will ignore this constraint by downgrading `conda-smithy` so as to get the latest `conda`.

TBH I'm pretty surprised that a minor version broke `conda-smithy` in such a basic way. The break here is we can no longer run the CLI not even `--help`. I'm starting to wonder if time might be better spent fixing `conda`.

**Pull request merged**
