### PR TITLE
Fixes replacement of UTF-16 and UTF-32 strings

### PR DESCRIPTION
**Pull request by hmaarrfk**
I made the PR upstream, but getting it faster would be appreciated too!
https://github.com/conda/conda/pull/9946

https://github.com/conda/conda/issues/4298

Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
failed on http error before build

**Comment by scopatz** [comment]
Restarting seemed to work

**Comment by hmaarrfk** [comment]
I should say that the patch merged was rejected due to the case that it might really slow down conda's installation procedure.

Do you want the latest patch, that scans the file once?

**Comment by mingwandroid** [comment]
Where is the single scan version? FWIW I am off the opinion that this should be done in conda-build and conda should only then do the replacements recorded by conda-build. Cc @kalefranz

**Comment by hmaarrfk** [comment]
Single scan version is in the PR
https://github.com/conda/conda/pull/9946

**Comment by hmaarrfk** [comment]
So technically two PRs are necessary:

1. The first to conda-build to identify UTF-16 and UTF-32 strings
2. The second to conda to be able to understand that replacement should be done using UTF-16 or UTF-32

That said, currently, binary files are scanned during install.
I understand that the ideal solution would be do it in conda-build, but that seems much harder seeing as it will require coordination between the two.

**Comment by mingwandroid** [comment]
I see a for loop in there? Doesn't seem single scan to me.

**Comment by hmaarrfk** [comment]
Right sorry. single scan for the binary replacement.

**Comment by hmaarrfk** [comment]
should we discuss this on that PR specifically?

**Pull request merged**
