### PR TITLE
Add archspec dependency

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

cc @conda-forge/core

### CODE REVIEW

**Review by kkraus14 — APPROVED** [review]

**Comment by kkraus14** [comment]
Thanks @isuruf 😄

**Comment by isuruf** [comment]
> There was an API change in [archspec 0.1.3](https://github.com/archspec/archspec/compare/v0.1.2...v0.1.3) for Apple ARM chips, where it stops returning arm64 and instead m1

That shouldn't be a problem. It's supposed to return a more specific name when archspec knows about the CPU and a generic name when it doesn't.

> breaking the assumptions of the archspec.cpu.host() call used in conda.

What are these assumptions?

**Comment by jezdez** [comment]
> > There was an API change in [archspec 0.1.3](https://github.com/archspec/archspec/compare/v0.1.2...v0.1.3) for Apple ARM chips, where it stops returning arm64 and instead m1
> 
> That shouldn't be a problem. It's supposed to return a more specific name when archspec knows about the CPU and a generic name when it doesn't.
> 
> > breaking the assumptions of the archspec.cpu.host() call used in conda.
> 
> What are these assumptions?

Just that so far it has been returning `arm64`, while now it's more specific.

**Comment by jezdez** [comment]
Oh, btw defaults has archspec 0.2.1 now as well

**Comment by isuruf** [comment]
> Just that so far it has been returning arm64, while now it's more specific.

Yes, that's fine. Without archspec I see `__archspec=1=x86_64` and with archspec it is `__archspec=1=zen3`, so it is expected and necessary for the microarchitecture detection.

**Review by beckermr — APPROVED** [review]
This PR only effects conda-forge and so I'd like to see it decoupled from the discussion of what is done with defaults.

**Comment by beckermr** [comment]
@jezdez can you take a look here so we can come to a conclusion on this?

**Review by jezdez — APPROVED** [review]

**Comment by jezdez** [comment]
> > Just that so far it has been returning arm64, while now it's more specific.
> 
> Yes, that's fine. Without archspec I see `__archspec=1=x86_64` and with archspec it is `__archspec=1=zen3`, so it is expected and necessary for the microarchitecture detection.

Thank you for elaborating

**Comment by beckermr** [comment]
Thank you @jezdez!

**Pull request merged**
