### PR TITLE
Bump constraint on conda-libmamba-solver.

### PR DESCRIPTION
**Pull request by jezdez**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jezdez** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
cc @dholth

**Review by dholth — APPROVED** [review]
Why not.

**Comment by jakirkham** [comment]
Submitted PR ( https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/367 ) to hot-fix the repodata for the previous package build. PTAL

**Pull request merged**
