### PR TITLE
require requests 2.20.1

### PR DESCRIPTION
**Pull request by dholth**
A future version of conda will have this (still quite old) minimum requests

### CODE REVIEW

**Review by dholth — COMMENTED** [review]
match https://github.com/conda/conda/pull/11643

**Comment by jakirkham** [comment]
Got it. So we don't want to merge this, but simply incorporate it in the next release. Is that right? If so, should we mark this as a draft to make that clearer?

**Comment by dholth** [comment]
It shouldn't matter when this is merged, but I suppose merging it early causes an unnecessary conda rebuild?

**Review by jezdez — APPROVED** [review]
Approving in preparation to 4.14.0 release.

**Pull request merged**
