### PR TITLE
Fix activate scripts

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/conda-forge/conda-feedstock/issues/1

This really needs a careful review. I think this is on the right track for fixing up the activation scripts. Though I really could use some help testing it (particularly on Windows).

### CODE REVIEW

**Comment by jakirkham** [comment]
Did some mild testing with this on Linux and it seems to be working.

**Comment by msarahan** [comment]
LGTM.  I don't know how careful a review can be.  We just need to try it and see.  Have you built packages with this?  Are they any better, just by inspection (are the activation scripts actually scripts, not links?)

**Comment by jakirkham** [comment]
So I just tested it on Linux thus far. Was able to install it and switch environments. The activation scripts were in fact scripts (not links). Will try Mac next, but I don't expect it will be too different. If you could try it on Windows, that would be really helpful. I sort of made my best guess there, but maybe it needs more tweaking on that platform.

**Comment by msarahan** [comment]
OK.  I'm done for tonight, but will pick it up tomorrow.

**Comment by jakirkham** [comment]
Mac also seems to do fine. Was able to create an environment, activate it, switch back to `root`, deactivate completely, and reactivate root.

**Comment by jakirkham** [comment]
Ok sounds good. Probably going to take a break myself.

**Comment by jakirkham** [comment]
Would you also have time to test this, @janschulz?

**Comment by janschulz** [comment]
@jakirkham Just clone and `conda build recipe/` resulted in a build failure:

```
λ conda build recipe\
Removing old build environment
BUILD START: conda-4.1.11-py35_0
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .................

WARNING: conda-build appears to be out of date. You have version 1.20.3 but the
latest version is 1.21.11. Run

conda update -n root conda-build

to get the latest version.

Solving package specifications: ..........

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    vs2015_runtime-14.0.25420  |                0         1.9 MB  conda-forge
    python-3.5.2               |                2        23.9 MB  conda-forge
    yaml-0.1.6                 |           vc14_0         100 KB  conda-forge
    certifi-2016.8.2           |           py35_0         219 KB  conda-forge
    conda-env-2.5.2            |           py35_0          67 KB  conda-forge
    pycosat-0.6.1              |           py35_0          45 KB  conda-forge
    pyyaml-3.11                |           py35_0         118 KB  conda-forge
    requests-2.10.0            |           py35_0         599 KB  conda-forge
    ruamel_yaml-0.11.14        |           py35_0         217 KB  defaults
    wincertstore-0.2           |           py35_0          10 KB  conda-forge
    setuptools-25.1.6          |           py35_0         493 KB  conda-forge
    wheel-0.29.0               |           py35_0         123 KB  conda-forge
    pip-8.1.2                  |           py35_0         1.6 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        29.4 MB

The following NEW packages will be INSTALLED:

    certifi:        2016.8.2-py35_0 conda-forge
    conda-env:      2.5.2-py35_0    conda-forge
    menuinst:       1.4.1-py35_0    defaults
    pip:            8.1.2-py35_0    conda-forge
    pycosat:        0.6.1-py35_0    conda-forge
    python:         3.5.2-2         conda-forge
    pyyaml:         3.11-py35_0     conda-forge
    requests:       2.10.0-py35_0   conda-forge
    ruamel_yaml:    0.11.14-py35_0  defaults
    setuptools:     25.1.6-py35_0   conda-forge
    vs2015_runtime: 14.0.25420-0    conda-forge
    wheel:          0.29.0-py35_0   conda-forge
    wincertstore:   0.2-py35_0      conda-forge
    yaml:           0.1.6-vc14_0    conda-forge [vc14]

Pruning fetched packages from the cache ...
Fetching packages ...
vs2015_runtime 100% |###############################| Time: 0:00:03 651.46 kB/s
python-3.5.2-2 100% |###############################| Time: 0:00:13   1.90 MB/s
yaml-0.1.6-vc1 100% |###############################| Time: 0:00:00 206.81 kB/s
certifi-2016.8 100% |###############################| Time: 0:00:00 254.60 kB/s
conda-env-2.5. 100% |###############################| Time: 0:00:00 193.80 kB/s
pycosat-0.6.1- 100% |###############################| Time: 0:00:00 193.94 kB/s
pyyaml-3.11-py 100% |###############################| Time: 0:00:00 253.49 kB/s
requests-2.10. 100% |###############################| Time: 0:00:01 389.76 kB/s
ruamel_yaml-0. 100% |###############################| Time: 0:00:00 246.64 kB/s
wincertstore-0 100% |###############################| Time: 0:00:00   3.47 MB/s
setuptools-25. 100% |###############################| Time: 0:00:01 385.15 kB/s
wheel-0.29.0-p 100% |###############################| Time: 0:00:00 213.12 kB/s
pip-8.1.2-py35 100% |###############################| Time: 0:00:02 665.64 kB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################| 100%
Source cache directory is: C:\portabel\miniconda\conda-bld\src_cache
Downloading source to cache: conda-4.1.11.tar.gz
Downloading https://github.com/conda/conda/archive/4.1.11.tar.gz
Success
Extracting download
Package: conda-4.1.11-py35_0
source tree in: C:\portabel\miniconda\conda-bld\work\conda-4.1.11
Error: Glob Scripts\\activate.bat from always_include_files does not match any files
```

**Comment by jakirkham** [comment]
So I think you have an old version of `conda-build`. Could you please try updating and repeating? `conda-build` isn't suppose to be this sensitive with `always_include_files` any more.

**Comment by janschulz** [comment]
Ok, updated conda-build, build conda, installed with `conda install --use-local conda` and activate was gone: 

```
c:\data\external\conda-packages\conda-feedstock (master)
λ activate py35
Der Befehl "activate" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
```

[Translation: no "activate" found in path]

**Comment by janschulz** [comment]
I uploaded the broken package to https://dl.dropboxusercontent.com/u/1839214/conda-4.1.11-py35_0.tar.bz2

**Comment by janschulz** [comment]
Maybe add this to the appveyor.yml file in this PR:

```
  - cmd: mkdir dist || cmd /c "exit /b 0"'
  - cmd: 'copy /Y %CONDA_INSTALL_LOCN%\conda-bld\win-32\*.bz2 dist || cmd /c "exit /b 0"'
  - cmd: 'copy /Y %CONDA_INSTALL_LOCN%\conda-bld\win-64\*.bz2 dist || cmd /c "exit /b 0"'
  - cmd: dir dist\
  - cmd: echo finished...

artifacts:
  - path: dist\*
    name: packages
```

**Comment by jakirkham** [comment]
Thanks @janschulz. This very helpful. I'll see what I can do. If there is anything obviously wrong that you can see, please let me know.

**Comment by jakirkham** [comment]
Note to self: Was built with commit ( https://github.com/conda-forge/conda-feedstock/commit/0b7b77e14425dc0a0d7843df17c079f3e6dcfbd3 ).

**Comment by janschulz** [comment]
Oups, wait, I only cloned the repo, not the PR...

**Comment by jakirkham** [comment]
FWIW there were still some things that were off with `always_include_files` and `bld.bat` so I updated them. Not sure that any of them would have caused that issue per se, but they may have caused other issues.

**Comment by janschulz** [comment]
Ok, build of 6e5fefb had still no `activate.bat` in `<root>\Scripts` :-(

**Comment by jakirkham** [comment]
Could you please share the new package?

**Comment by janschulz** [comment]
I poked into the `info\files` dir in the tar.bz2 file and only found this

```
[...]
Scripts/conda-script.py
Scripts/conda-script.pyc
Scripts/conda.exe
etc/fish/conf.d/conda.fish
exec/activate
exec/activate.bat
exec/conda-script.py
exec/conda-script.pyc
exec/conda.bat
exec/conda.exe
exec/deactivate
``` 

But in the work env, these files are there, so I guess conda build doesn't package them...

Hm, have you tried setting the ingore files to unix slashes? This line https://github.com/conda/conda-build/blob/master/conda_build/build.py#L262 indicates that internally conda compares the ingore list to files with unix slashes.

**Comment by jakirkham** [comment]
Ah, so `/` should work. Sure we can try that.

**Comment by jakirkham** [comment]
Yep, looks like the `/` makes the difference. At least that is what the AppVeyor artifact suggests. Could you please give this one a try, @janschulz?

**Comment by janschulz** [comment]
Yes, can confirm that c1ed513 works on my system (after I did `conda install --use-local conda -f` (I really hate that conda doesn't compare the sha/timestamp of packages with the local unpacked version...))

**Comment by jakirkham** [comment]
Raised issue ( https://github.com/conda/conda-build/issues/1194 ) about supporting a double backslash in that code path.

**Comment by jakirkham** [comment]
Alright, I'm going to bravely remove the WIP as this seems ready (famous last words 😆). We have now tested on all OSes at least once. While it couldn't hurt for more people to test this, I don't know that we will find anything different.

**Comment by janschulz** [comment]
Raised https://github.com/conda/conda/issues/3255 for my "WTF" problem with the package not working when doing the testing :-)

**Comment by msarahan** [comment]
Thanks @janschulz and @jakirkham.  @jakirkham, I'm +1 for merge here.  @janschulz do you want to be a maintainer here.

**Comment by jakirkham** [comment]
> @janschulz do you want to be a maintainer here?

👍

**Comment by janschulz** [comment]
Thanks, but no: I'm fine with lurking and will subscribe here, but I'm actually already full with other projects. Sometimes I have the feeling I'm the only one actually doing dev work on windows, everybody else is linux/mac :-/

**Comment by jakirkham** [comment]
There are a couple other Windows people. Actually there aren't so many Mac people. It is just Mac is very similar to Linux. So many people can get something working on both with relatively little effort.

**Comment by msarahan** [comment]
The deep end of Mac is pretty deep.  It's true that most knowledge for Linux also applies, but man I hate it when Mac (or BSD or whatever) is too different.  It can get really ugly very quickly.

**Comment by jakirkham** [comment]
Thanks guys. Appears all builds have been released.

Let's remain vigilant. 👀 👂 Please let me know if there are issues and I will happily pull it.

**Comment by jakirkham** [comment]
FWIW this PR ( https://github.com/conda-forge/coverage-feedstock/pull/2 ) appears to be using all `conda` from `conda-forge` for all builds. So it should be a good test case. Thus far it seems to be doing ok.

**Pull request merged**
