### PR TITLE
update conda to 4.2

### PR DESCRIPTION
**Pull request by kalefranz**
Closes https://github.com/conda-forge/conda-feedstock/pull/4

Conda 4.2 is being prepared for GA.  Will update this PR once it's ready.

### CODE REVIEW

**Comment by jakirkham** [comment]
Should I read this [comment]( https://github.com/conda-forge/conda-env-feedstock/pull/1#issuecomment-247209346 ) as this is ready?

**Comment by kalefranz** [comment]
It's ready indeed!

**Comment by kalefranz** [comment]
Just bumped to 4.2.7.

**Comment by kalefranz** [comment]
We''re at 4.2.9 now.  Anyone?

**Comment by jakirkham** [comment]
Am waiting for @mcg1969 or @msarahan to sign off on/merge PR ( https://github.com/conda-forge/conda-env-feedstock/pull/1 ) just as you.

**Comment by mcg1969** [comment]
As discussed with @kalefranz I'd like to make sure @msarahan is good with the signoff here because of the interaction with conda build.

**Comment by msarahan** [comment]
Fine with me.  Things seem to be working fine for me with conda 4.2 and conda-build 2.0.2.

**Comment by jakirkham** [comment]
Note: Added a "closes" line in the OP to close out an older PR in the same vein.

**Comment by tacaswell** [comment]
I think this will fix https://github.com/conda/conda-build/issues/1459 which is breaking mpl's appveyor builds :/

**Comment by msarahan** [comment]
@tacaswell sorry about that.  I am tagging 2.0.6 momentarily just for that big fubar.

**Comment by tacaswell** [comment]
@msarahan No worries, greatly appreciate that your are fixing it!

**Comment by msarahan** [comment]
@tacaswell 2.0.6 should be available.

**Comment by mwcraig** [comment]
@kalefranz -- looks like this needs a rebase now (and may as well bump to 4.2.9, I suppose). It would be nice to get this merged soon so that the conda-forge `conda` is not so far behind....

**Comment by kalefranz** [comment]
I just released conda 4.2.11 tonight.  I'll update the PR, but I won't merge it; I don't want to merge my own PR.  Another maintainer or someone else from conda-forge will need to hit the merge button.

**Comment by mwcraig** [comment]
@kalefranz -- could you please restart the failed appveyor build?

**Comment by kalefranz** [comment]
For whoever ultimately clicks the merge button, I *highly* recommend you make https://github.com/conda-forge/conda-env-feedstock/pull/1 available first.

Actually, conda won't even install without it.  But I guess most people would probably fall back to the conda-env in the defaults channel.

**Comment by mwcraig** [comment]
Though I see the green merge buttons, I'm not technically a maintainer on either conda or on conda-env. 

Sounds like there is some limited potential for someone getting a bad combination of conda/conda-env (https://github.com/conda-forge/conda-env-feedstock/pull/1) but that opportunity should exist only for a narrow window of time.

@msarahan or @mcg1969 can you please merge  the conda-env PR and then this one? We could wait until late tonight if that would help minimize potential conflitcts (and the CI services are faster then).

**Comment by kalefranz** [comment]
Ok guys it's time someone takes action on this.  Feel free to remove me as a maintainer if anyone feels I'm acting inappropriately.  But I'm going to go ahead and merge conda and conda-env.  I think it's safest to merge them at about the same time, with most people likely having `defaults` as a backup.

**Comment by mwcraig** [comment]
>  But I'm going to go ahead and merge conda and conda-env. 

+1 -- this needed to move forward, I think.

**Pull request merged**
