### PR TITLE
Create recipe for sciplot

### PR DESCRIPTION
**Pull request by allanleal**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by allanleal** [comment]
@conda-forge-admin, please rerender

**Comment by allanleal** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
I believe that you do not want to target this feedstock. This is the conda recipe, not sciplot.
I'm closing this to avoid wasting CIs resources and ping the cnoda team but feel free to send a PR to https://github.com/conda-forge/staged-recipes if you want to add sciplot to conda-forge and create a feedstock for it.

**Comment by allanleal** [comment]
Oh, my bad. Thanks for pointing this out.

**Comment by jjhelmus** [comment]
@allanleal You should submit new recipes to the [stage-recipes repositories](https://github.com/conda-forge/staged-recipes/) not here.  This is the feedstock which creates the conda package itself.  These [docs for contributing packages](https://conda-forge.org/docs/maintainer/adding_pkgs.html#) might be helpful

**Comment by ocefpaf** [comment]
jj

**Pull request closed without merging**
