### PR TITLE
Regro cf autotick bot 4.6.0

### PR DESCRIPTION
**Pull request by mariusvniekerk**
Closes #68 

Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mariusvniekerk** [comment]
@conda-forge-admin please reremder

**Comment by mariusvniekerk** [comment]
@conda-forge-admin please rerender

**Comment by scopatz** [comment]
:tada:

**Comment by saraedum** [comment]
I now see the issue described in https://github.com/conda/conda/issues/4903#issuecomment-423598897 in a feedstock build.

```
+ setup_conda_rc /home/conda/feedstock_root /home/conda/recipe_root /home/conda/feedstock_root/.ci_support/linux_.yaml
+ conda clean --lock

ArgumentError: At least one removal target must be given. See 'conda clean --help'.

Exited with code 2
```

**Comment by mariusvniekerk** [comment]
@saraedum we've released a new version of conda-smithy that deals with this

**Pull request merged**
